// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiProject.Infrastructure.Db;

namespace WebApiProject.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220304203218_AddProductsAndCategoriesTables")]
    partial class AddProductsAndCategoriesTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApiProject.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Food"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cosmetics"
                        });
                });

            modelBuilder.Entity("WebApiProject.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            IsAvailable = true,
                            Name = "Tea",
                            Price = 19.99m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            IsAvailable = true,
                            Name = "Milk",
                            Price = 30.00m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            IsAvailable = false,
                            Name = "Bread",
                            Price = 18.20m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            IsAvailable = false,
                            Name = "Sony Xperia 1",
                            Price = 16420.75m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            IsAvailable = true,
                            Name = "Xiaomi Redmi 9",
                            Price = 6969.42m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            IsAvailable = false,
                            Name = "Meizu m8 Note",
                            Price = 5999.99m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            IsAvailable = true,
                            Name = "Cream",
                            Price = 100.01m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            IsAvailable = true,
                            Name = "Shampoo",
                            Price = 59.80m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            IsAvailable = false,
                            Name = "Tonic",
                            Price = 80.14m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            IsAvailable = true,
                            Name = "Eyeshadow",
                            Price = 401.25m
                        });
                });

            modelBuilder.Entity("WebApiProject.Domain.Entities.Product", b =>
                {
                    b.HasOne("WebApiProject.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebApiProject.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
