// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiProject.Infrastructure.Db;

namespace WebApiProject.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220221165339_CreateProductTable")]
    partial class CreateProductTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApiProject.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAvailable = true,
                            Name = "Tea",
                            Price = 1.99m
                        },
                        new
                        {
                            Id = 2,
                            IsAvailable = true,
                            Name = "Milk",
                            Price = 0.99m
                        },
                        new
                        {
                            Id = 3,
                            IsAvailable = false,
                            Name = "Carpet",
                            Price = 0.50m
                        },
                        new
                        {
                            Id = 4,
                            IsAvailable = false,
                            Name = "Bread",
                            Price = 0.75m
                        },
                        new
                        {
                            Id = 5,
                            IsAvailable = true,
                            Name = "Shoes",
                            Price = 5.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
